AWSTemplateFormatVersion: '2010-09-09'
Description: >
  Creates a CodeBuild Project to pull the GitHub repository,
  build a Docker Image based on the repository. It will then push the
  Image to a Container Repository.
Resources:
  DockerBuilder:
    Type: 'AWS::CodeBuild::Project'
    Properties:
      Name: mellon_docker
      Description: 'Build Docker Image from GitHub'
      ServiceRole: !ImportValue 'codebuild:role' # This exists in testlibND but I think I would rather create a role within this CF, reference it [and also export it for later]
      TimeoutInMinutes: 10
      Source:
        Type: GITHUB
        Location: 'https://github.com/ndlib/image-server.git'
      Artifacts:
        Type: NO_ARTIFACT
        Packaging: NONE
        NamespaceType: BUILD_ID
        Name: build
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_MEDIUM
        Image: 'centos:6'
        EnvironmentVariables:
          - Name: APPLICATION_NAME
            Value: ndlib-image-server
