
Parameters:

  InfrastructureStackName:
    Type: String
    Default: mellon-app-infrastructure
    Description: The name of the parent infrastructure/networking stack that you created. Necessary
                 to locate and reference resources created by that stack.

  EnvType:
    Type: String
    Description: The type of environment to create.
    Default: dev
    AllowedValues:
      - dev
      - prod
    ConstraintDescription: must specify prod or dev.

Mappings:
  # Settings to use for each environment.
  EnvTypeSettings:
    dev:
      CorsOrigins:
        - "*.library.nd.edu"
        - "*.cloudfront.net"
        - "http://universalviewer.io"
    prod:
      CorsOrigins:
        # This will probably need to change to allow overrides via params somehow,
        # but not going to fight it now since this is a place holder for data-broker
        - "*.library.nd.edu"

Outputs:

  PublicBucket:
    Description: A temporary bucket to share assets publicly for Mellon project
    Value: !Ref PublicBucket

Resources:

  PublicBucketParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Type: String
      Name: !Sub '/all/stacks/${AWS::StackName}/publicbucket'
      Value: !Ref PublicBucket
      Description: The name of the public bucket for IIIF Services

  PublicBucket:
    Type: AWS::S3::Bucket
    Properties:
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders: ['*']
            AllowedOrigins: !FindInMap [EnvTypeSettings, !Ref EnvType, "CorsOrigins"]
            AllowedMethods: [GET]
            MaxAge: 3600
      LoggingConfiguration:
        DestinationBucketName:
          Fn::ImportValue: !Join [':', [!Ref InfrastructureStackName, 'LogBucket']]
        LogFilePrefix: s3/data-broker/
      WebsiteConfiguration:
        IndexDocument: index.html

  PublicBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref PublicBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - s3:GetObject
            Resource: !Sub ${PublicBucket.Arn}/*
            Principal: '*'
