AWSTemplateFormatVersion: '2010-09-09'
Description: >
  Creates set of CloudWatch Event Rules to monitor a CI/CD pipeline.
  The target pipleine must have the following build stages:
    Source, Build, DeployToTest, Approval, DeployToProduction

  Expects the following exports from the target pipeline stack:
    - PipelineStackName:PipelineName

Parameters:
  PipelineStackName:
    Type: String
    Description: The name of the parent stack that created the pipeline to observe.

  Receivers:
    Type: String
    Description: An e-mail address to send the notifications to

Resources:

  PipelineEventsTopic:
    Type: AWS::SNS::Topic

  PipelineEventsTopicSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      TopicArn: !Ref PipelineEventsTopic
      Protocol: email
      Endpoint: !Ref Receivers

  # Allow events below to publish to the pipeline events topic
  EventTopicPolicy:
    Type: 'AWS::SNS::TopicPolicy'
    Properties:
      PolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: events.amazonaws.com
            Action: 'sns:Publish'
            Resource: !Ref PipelineEventsTopic
      Topics:
        - !Ref PipelineEventsTopic

  # Top level pipeline change events
  PipelineGenericEventRule:
    Type: AWS::Events::Rule
    Properties:
      Description: "Sends generic pipeline state change messages to the pipeline events topic."
      EventPattern:
        source:
          - aws.codepipeline
        detail-type:
          - "CodePipeline Pipeline Execution State Change"
        detail:
          pipeline:
            - Fn::ImportValue: !Join [':', [!Ref PipelineStackName, 'PipelineName']]
          state:
            - STARTED
            - SUCCEEDED
            - RESUMED
            - FAILED
            - CANCELED
            - SUPERSEDED
      State: "ENABLED"
      Targets:
        -
          Arn:
            Ref: "PipelineEventsTopic"
          Id: "PipelineEventsTopic"
          InputTransformer:
            InputPathsMap:
              Pipeline: "$.detail.pipeline"
              PipelineState: "$.detail.state"
            InputTemplate: !Sub '"The pipeline <Pipeline> has changed state to <PipelineState>. To view the pipeline, go to https://${AWS::Region}.console.aws.amazon.com/codepipeline/home?region=${AWS::Region}#/view/<Pipeline>."'
