---
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Description: 'Static host for webcomponents and single-page applications'


Parameters:

  InfrastructureStackName:
    Type: String
    Default: mellon-app-infrastructure
    Description: The name of the parent infrastructure/networking stack that you created. Necessary
                 to locate and reference resources created by that stack.

  DomainStackName:
    Type: String
    Default: mellon-domain
    Description: The name of the parent domain stack that you created. Necessary
                 to locate and reference resources created by that stack.

  CreateDNSRecord:
    Type: String
    Default: "True"
    Description: If True, will attempt to create a Route 53 DNS record for the CloudFront.

  SubDomain:
    Type: String
    Description: Host DNS name for website without Domain
    MaxLength: 63
    AllowedPattern: ^$|(?!-)[a-zA-Z0-9-.]{1,63}(?<!-)
    ConstraintDescription: Must be a valid SubDomain value.

  EnvType:
    Type: String
    Description: The type of environment to create.
    Default: dev
    AllowedValues:
      - dev
      - prod
    ConstraintDescription: must specify prod or dev.

Mappings:
  CacheSettings:
    dev:
      DefaultTTL: 0
    prod:
      DefaultTTL: 86400

Conditions:

  CreateDNS: !Equals [ !Ref CreateDNSRecord, 'True' ]

Outputs:

  BucketName:
    Description: Name of S3 bucket to hold website content
    Value: !Ref Bucket
    Export:
      Name: !Join [ ':', [ !Ref 'AWS::StackName', 'BucketName']]

  URL:
    Description: The FQDN if one is given, otherwise the cloudfront distribution domain name.
    Value: !Sub
        - '${SubDomain}.${ResolvedDomainName}'
        - ResolvedDomainName:
            Fn::ImportValue: !Sub '${DomainStackName}:DomainName'
    Export:
      Name: !Join [ ':', [ !Ref 'AWS::StackName', 'URL']]

  DistributionDomainName:
    Description: The cloudfront distribution domain name.
    Value: !GetAtt Distribution.DomainName

Resources:

  OriginAccessIdentity:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: !Sub Static assets in ${AWS::StackName}

  Bucket:
    Type: AWS::S3::Bucket
    Properties:
      LoggingConfiguration:
        DestinationBucketName:
          Fn::ImportValue: !Join [':', [!Ref InfrastructureStackName, 'LogBucket']]
        LogFilePrefix: !Sub
            - 's3/${SubDomain}.${ResolvedDomainName}/'
            - ResolvedDomainName:
                Fn::ImportValue: !Sub '${DomainStackName}:DomainName'

  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref Bucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - s3:GetObject
            Resource: !Sub ${Bucket.Arn}/*
            Principal:
              CanonicalUser: !GetAtt OriginAccessIdentity.S3CanonicalUserId

  Route53DNSCreation:
    Type: AWS::Route53::RecordSet
    Condition: CreateDNS
    Properties:
      HostedZoneName: !Sub
        - '${ResolvedDomainName}.'
        - ResolvedDomainName:
            Fn::ImportValue: !Sub '${DomainStackName}:DomainName'
      Comment: !Sub
        - '${SubDomain}.${ResolvedDomainName}'
        - ResolvedDomainName:
            Fn::ImportValue: !Sub '${DomainStackName}:DomainName'
      Name: !Sub
        - '${SubDomain}.${ResolvedDomainName}'
        - ResolvedDomainName:
            Fn::ImportValue: !Sub '${DomainStackName}:DomainName'
      Type: CNAME
      TTL: '900'
      ResourceRecords:
        - !GetAtt Distribution.DomainName

  Distribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        HttpVersion: http2
        PriceClass: PriceClass_100
        ViewerCertificate:
          AcmCertificateArn:
              Fn::ImportValue: !Join [':', [!Ref DomainStackName, 'ACMCertificateARN']]
          MinimumProtocolVersion: TLSv1.1_2016
          SslSupportMethod: sni-only
        Comment: !Sub
            - '${SubDomain}.${ResolvedDomainName}'
            - ResolvedDomainName:
                Fn::ImportValue: !Sub '${DomainStackName}:DomainName'
        Aliases:
          - !Sub
              - '${SubDomain}.${ResolvedDomainName}'
              - ResolvedDomainName:
                  Fn::ImportValue: !Sub '${DomainStackName}:DomainName'
        DefaultRootObject: index.html
        DefaultCacheBehavior:
          ForwardedValues:
            QueryString: false
          AllowedMethods:
            - HEAD
            - GET
            - OPTIONS
          Compress: true
          DefaultTTL: !FindInMap [CacheSettings, !Ref EnvType, "DefaultTTL"]
          ViewerProtocolPolicy: redirect-to-https
          TargetOriginId: Bucket
          LambdaFunctionAssociations:
              -
                EventType: origin-request
                LambdaFunctionARN: !Ref SPARedirectionLambda.Version
        Origins:
          - Id: Bucket
            DomainName: !GetAtt Bucket.DomainName
            S3OriginConfig:
              OriginAccessIdentity: !Join
                - /
                - - origin-access-identity
                  - cloudfront
                  - !Ref OriginAccessIdentity
        Logging:
          # This should result in "logbucketname.s3.amazonaws.com", where "logbucketname" is the value from an export
          # named "InfrastructureStackName:LogBucket"
          Bucket: !Join
            - .
            - - !ImportValue
                Fn::Join: [':', [!Ref InfrastructureStackName, 'LogBucket']]
              - s3
              - !Ref AWS::URLSuffix
          Prefix: !Sub
               - 'web/${SubDomain}.${ResolvedDomainName}/'
               - ResolvedDomainName:
                   Fn::ImportValue: !Sub '${DomainStackName}:DomainName'
          IncludeCookies: true

  LambdaEdgeBasicExecutionRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: "Allow"
            Principal:
              Service:
                - "lambda.amazonaws.com"
                - "edgelambda.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      Path: "/"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole

  SPARedirectionLambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./src/unifiedEdgeLambda/handler.js
      Description: Basic rewrite rule to send directory requests to appropriate locations in the SPA
      Handler: handler.handler
      Role: !GetAtt LambdaEdgeBasicExecutionRole.Arn
      Runtime: nodejs8.10
      AutoPublishAlias: live
